import {Injectable} from '@angular/core';
import {MinimalEvent} from '../models/min-event.model';
import {Location} from '../models/location.model';

@Injectable()
export class MinimalEventService {
  events: MinimalEvent[] = [
    new MinimalEvent('Projectweek 2018-2019', 'Tijdens de projectweek werden verschillende gastsprekers uitgenodigd aan de Hogeschool PXL. Tijdens deze week werd de Thalento test ook ingevuld en onze teamleden voor het research project bekend gemaakt.', [new Location('PXL', 'Elfde-Liniestraat 24 3500 Hasselt')], [new Date('2019-02-11'), new Date('2019-02-12'), new Date('2019-02-13'), new Date('2019-02-14'), new Date('2019-02-15')], 26, false),
    new MinimalEvent('Innovatieroute AR en VR', 'Deze innovatieroute gaf een beter inzicht in het begrijpen van VR. De eerste dag was een snelcursus Unity, de twee daaropvolgende dagen hadden betrekking op Unreal Engine.', [new Location('PXL', 'Elfde-Liniestraat 24 3500 Hasselt'), new Location('Uncanny', 'Kempische Steenweg 293, 3500 Hasselt')], [new Date('2019-09-25'), new Date('2019-10-02'), new Date('2019-10-03')], 24, false),
    new MinimalEvent('POP-sessies', 'Tijdens de POP sessies verkregen we meer uitleg over samenwerking in teamverband, het onderscheid tussen hoofd- en bijzaken, en leerden we onze teamgenoten beter kennen.', [new Location('PXL', 'Elfde-Liniestraat 24 3500 Hasselt')], [new Date('2019-10-04')], 10, false),
    new MinimalEvent('De Warmste Hackathon', 'Dit was de eerste editie van De Warmste Hackathon, opgericht door Realdolmen. In groep werkten we een idee uit om de wereld te verbeteren, namelijk een applicatie voor verschillende gezelschapsspellen.', [new Location('Realdolmen', 'Stormstraat 2, 1000 Brussel')], [new Date('2019-10-11'), new Date('2019-10-12')], 16, true),
    new MinimalEvent('Seminarie: Introductie tot het bouwen van een chatbot & voice assistant', 'Mathias Vissers van Intracto gaf hier enthousiast een presentatie rond Dialogflow, een Natural Language Processing platform van Google.', [new Location('Intracto', 'Elfde-Liniestraat 24, 3500 Hasselt')], [new Date('2019-11-06')], 3, false),
    new MinimalEvent('Seminarie: Op weg naar 5G', 'Met dit seminarie werd door beide gastlezers een korte geschiedenis geschetst van de ontwikkeling van telefoonnetwerken. Hierna werd er uitleg gegeven over 5G.', [new Location('Ericsson', 'Elfde-Liniestraat 24, 3500 Hasselt')], [new Date('2019-11-27')], 3, false),
    new MinimalEvent('Seminarie: React Native: cross-platform mobile app development', 'Bij dit seminarie werd de geschiedenis van React uitgelegd, gevolgd door de voor- en nadelen van React Native. Het grootste deel van dit seminarie bestond echter uit een live demo.', [new Location('AppFoundry', 'Elfde-Liniestraat 24, 3500 Hasselt')], [new Date('2019-12-18')], 3, false),
    new MinimalEvent('Seminarie: Flying us to a smarter future', 'Tijdens dit ontbijtseminarie gaf de CEO van Droneport, Mark Vanlook, uitleg over de verschillende soorten drones. Eveneens gaf hij een bondige omschrijving van zijn bedrijf.', [new Location('Droneport', 'Elfde-Liniestraat 24, 3500 Hasselt')], [new Date('2019-02-20')], 2, false),
    new MinimalEvent('Seminarie: Don’t make me think', 'Superlabs medeoprichter Geert Tewissen vertelde hier hoe we een intuïtieve userinterface kunnen opstellen.', [new Location('Superlab', 'Elfde-Liniestraat 24, 3500 Hasselt')], [new Date('2019-02-27')], 3, false),
    new MinimalEvent('De Vlaamse Programmeer Wedstrijd', 'Tijdens de Vlaamse Programmeer Wedstrijd van 2019 moesten er teams van drie personen aan één computer verscheidene programmeervraagstukken oplossen.', [new Location('Vlaamse Programmeer Wedstrijd', 'Ellermanstraat 33, 2060 Antwerpen')], [new Date('2019-03-13')], 3, true),
    new MinimalEvent('Seminarie: The modular monolith', 'Het publiek kreeg bij dit seminarie, gegeven door Bert Roex, een uitgebreide beschrijving over monolithische applicaties.', [new Location('XTi', 'Elfde-Liniestraat 24, 3500 Hasselt')], [new Date('2019-03-20')], 4, false),
    new MinimalEvent('Seminarie: Test-driven development', 'Drie werknemers van ACA IT-Solutions gaven de opdracht om met een Kanban bord een test-driven scenario te simuleren. Er werd een project voorzien waarin opzettelijk fouten waren aangebracht.', [new Location('ACA IT-Solutions', 'Herkenrodesingel 8b, 3500 Hasselt')], [new Date('2019-03-27')], 3, false),
    new MinimalEvent('Seminarie: De wonderwereld van Firebase', 'Dit seminarie was een eerste initiatie tot Firebase, een NoSQL alternatief van datastorage aangeboden door google. Het merendeel van dit seminarie werd gevolgd aan de hand van een live demo.', [new Location('Evance', 'Kempische Steenweg 293, 3500 Hasselt')], [new Date('2019-04-03')], 3, false),
    new MinimalEvent('Seminarie: Facebook en ik', 'Tim Verheyden van de VRT gaf met een ontbijtseminarie aan de Hogeschool PXL een live bespreking over zijn succesreportage “Facebook en ik”.', [new Location('PXL in samenwerking met Tim Verheyden', 'Elfde-Liniestraat 24, 3500 Hasselt')], [new Date('2019-10-04')], 2, false),
    new MinimalEvent('Studiereis: Berlijn optie 2', 'Gedurende deze vijfdaagse uitstap naar Berlijn werden verschillende culturele locaties bezocht, zoals de Brandenburger Tor en de Gendarmenmarkt.', [new Location('PXL', 'Elfde-Liniestraat 24, 3500 Hasselt')], [new Date('2019-02-14'), new Date('2019-02-15'), new Date('2019-02-16'), new Date('2019-02-17'), new Date('2019-02-18')], 30, false),
    new MinimalEvent('De care-athon', 'Tijdens deze hackathon werd op twee dagen tijd geprobeerd om een applicatie te ontwikkelen om met gezichtsherkenning kinderen in en uit te scannen voor opvanglocaties.', [new Location('PXL in samenwerking met Cegeka, Xplore Group en Corda Campus', 'Kempische Steenweg 307, 3500 Hasselt')], [new Date('2020-02-20'), new Date('2020-02-21')], 26, false),
  ];

  constructor() {}

}
